name: Update Git Submodules

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC
  workflow_dispatch:
    

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git submodule update --remote --recursive

      - name: Commit and push updated submodules
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -m "Automated submodule update"
          git push
